# Generated by Django 3.0.2 on 2020-07-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='template_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
