# Generated by Django 3.0.2 on 2020-07-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='heading1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='heading2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='heading3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='para1',
            field=models.TextField(null=True),
        ),
    ]
