# Generated by Django 3.0.2 on 2020-07-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200716_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heading4',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='heading1',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='heading2',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='heading3',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
