# Generated by Django 3.0.2 on 2020-07-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_ost'),
    ]

    operations = [
        migrations.AddField(
            model_name='ost',
            name='title',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
