# Generated by Django 3.0.2 on 2020-07-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200730_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(max_length=800),
        ),
    ]
