# Generated by Django 3.0.2 on 2020-07-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20200730_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='url',
        ),
    ]
