# Generated by Django 3.0.2 on 2020-08-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20200802_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
