# Generated by Django 3.0.2 on 2020-08-02 08:41

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20200802_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='heading1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='heading2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='heading3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='heading4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='para1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='template_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
